changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: Data updates
      labels: [data]
    - title: Features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Maintenance
      labels: [dependencies, documentation]
    - title: Other changes
      labels: ["*"]
